name: samdul

services:
  blog:
    build: ./docker/httpd
    ports:
      - 80
    deploy:
      mode: replicated
      replicas: 1

  nginx:
    build: ./docker/nginx
    container_name: blog_lb
    ports:
      - "8949:80"
    depends_on:
      - blog

